server:
  port: 9001
  shutdown: graceful # 启动优雅关机
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # 优雅关机的超时时间，单位为秒
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      request-connect-timeout: 5000 # 等待连接配置服务器的超时时间，单位为毫秒
      request-read-timeout: 5000 # 等待从配置服务器读取数据的超时时间，单位为毫秒
      fail-fast: false # 允许应用在配置服务器不可用时启动
      retry:
        max-attempts: 6 # 最大尝试次数
        initial-interval: 1000 # Backoff初始间隔时间，单位为毫秒
        max-interval: 2000 # Backoff最大间隔时间，单位为毫秒
        multiplier: 1.1 # Backoff间隔时间的乘数，增加重试之间的等待时间
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 # 从池中获取连接的超时时间，单位为毫秒
      maximum-pool-size: 5 # 连接池的最大连接数
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    org.springframework.security: debug

info:
  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, metrics, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always #始终显示应用健康状态的详情
      show-components: always # 始终显示应用所使用组件的详情
      probes:
        enabled: true # 启用对健康探针的支持
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # 添加一个带有应用名称的Micrometer通用标签。这会将一个Prometheus标记应用到所有度量中

polar:
  greeting: Welcome to the local book catalog!
